### ISSUE TITLE
Fix list update in set() method

### ISSUE THREAD

**Issue by MistaKilla** [princeparadoxes/RecyclerBindableAdapter#2]
instead of [notifyItemsRangeChanged()](https://github.com/princeparadoxes/RecyclerBindableAdapter/blob/master/library/src/main/java/com/danil/recyclerbindableadapter/library/RecyclerBindableAdapter.java#L65) you should use `notifyItemChanged()`
because `item.set()` change only one item, no need to update part of list

**Comment by princeparadoxes** [comment]
Thank you. I did not pay attention to it
