### ISSUE TITLE
Merge conflict for AndroidManifests

### ISSUE THREAD

**Issue by cosic** [princeparadoxes/RecyclerBindableAdapter#4]
```
Attribute application@allowBackup value=(false) from AndroidManifest.xml:32:9-36
    is also present at [com.github.princeparadoxes:recyclerbindableadapter:1.2.1] AndroidManifest.xml:12:9-35 value=(true).
    Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:12:5-20:19 to override.
```

You should remove `android:allowBackup="true"` from library `AndroidManifest.xml`. Because it's unnecessary unnecessary.

**Comment by princeparadoxes** [comment]
In 1.3 version it's fixed

**Comment by cosic** [comment]
@princeparadoxes You should create a `CHANGELOG.md` with release notes like as at [an other repositories](https://github.com/square/picasso/blob/master/CHANGELOG.md). And change name of `Readme.md` on `README.md`
